# VGG Model Structures

# TODO: VGG 11, 13 will be implemented.

VGG16:
  [
    64,
    64,
    "M",
    128,
    128,
    "M",
    256,
    256,
    256,
    "M",
    512,
    512,
    512,
    "M",
    512,
    512,
    512,
    "M"
  ]


VGG19:
  [
    64,
    64,
    "M",
    128,
    128,
    "M",
    256,
    256,
    256,
    256,
    "M",
    512,
    512,
    512,
    512,
    "M",
    512,
    512.
    512,
    512,
    "M"
  ]

